[package]
name = "android_api_util"
version = "0.1.0"
authors = ["Patrik Buhring <patrikbuhring@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndk-glue = "0.3.0"
jni = "0.19.0"
